# Generated by Django 4.1.2 on 2022-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_review_review_user_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
