apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watchmate
  template:
    metadata:
      labels:
        app: watchmate
    spec:
      containers:
      - name: k8s-web
        image: cyrilbaah/watchmate
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: django-insecure-ig!sz9s%$o4gn&@rpo@qp#rn$-!==bb9hc#iptl^i#)aj24trq
        - name: DB_TYPE
          value: postgres
        - name: USE_S3
          value: 'False'
        - name: DB_NAME
          value: watchmate
        - name: DB_HOST
          value: aegis-live.ck0dwzfc16xf.eu-west-1.rds.amazonaws.com
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: amalitech
        - name: DB_PORT
          value: '5432'
